apiVersion: v1
kind: Pod
spec:
  serviceAccountName: jenkins-sa

  containers:
    - name: node
      image: node:24
      command:
        - cat
      tty: true

    - name: docker
      image: docker:27-dind
      securityContext:
        privileged: true
      env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
      tty: true

    - name: kubectl
      image: bitnami/kubectl:latest
      command:
        - cat
      tty: true
